const extraBooks=[
{slug:'hen-tent',title:'The Hen in the Tent',job:'Consolidate',focus:'e · h · n',cover:'🐔',pages:[['A hen hid in a tent.','hen','h → e → n','🐔 ⛺','#edf7f4'],['Dad had a red hat.','hat','h → a → t','👨‍🦱 🎩','#fff4d6'],['Dad set the hat in the tent.','tent','t → e → n → t','🎩 ⛺','#dceff5'],['The hen sat on the hat.','sat','s → a → t','🐔 🎩','#fce1e6'],['Dad did not get the hat.','get','g → e → t','👨‍🦱 🔎','#fff4d6'],['Cluck! The hat ran.','ran','r → a → n','🎩 🐔 💨','#edf7f4'],['Dad got the hat. The hen got the tent.','got','g → o → t','👨‍🦱 🎩 · 🐔 ⛺','#dceff5']]},
{slug:'mud-bus',title:'Mud on the Bus',job:'Consolidate',focus:'u · m · d',cover:'🚌',pages:[['A bus hit mud.','mud','m → u → d','🚌 🟤','#fff4d6'],['Mud sat on the bus.','bus','b → u → s','🚌 🟤','#edf7f4'],['A kid got a rag.','rag','r → a → g','🧒 🧽','#dceff5'],['Rub, rub, rub.','rub','r → u → b','🧒 🚌','#fce1e6'],['A pup ran up.','pup','p → u → p','🐕 💨','#fff4d6'],['The pup fell in the mud.','fell','f → e → ll','🐕 🟤','#edf7f4'],['The bus was not sad. It had a mud pup.','pup','p → u → p','🚌 🐕','#dceff5']]},
{slug:'fox-box',title:'The Fox in the Box',job:'Consolidate',focus:'x · o',cover:'🦊',pages:[['A fox had a box.','fox','f → o → x','🦊 📦','#fce1e6'],['The fox had a nap.','nap','n → a → p','🦊 Zzz','#edf7f4'],['Dad put the box in a van.','van','v → a → n','📦 🚐','#fff4d6'],['The van did go.','van','v → a → n','🚐 💨','#dceff5'],['Pop! Up sat the fox.','fox','f → o → x','📦 🦊','#fce1e6'],['Dad did stop the van.','stop','s → t → o → p','👨‍🦱 ✋ 🚐','#edf7f4'],['The fox got the box. Dad got a shock.','shock','sh → o → ck','🦊 📦 · 😮','#fff4d6']]},
{slug:'lost-sock',title:'Kiki and the Lost Sock',job:'Teach',focus:'ck',cover:'🧦',pages:[['Kiki had a red sock.','sock','s → o → ck','👧 🧦','#fff4d6'],['The sock sat on a cot.','sock','s → o → ck','🧦 🛏️','#edf7f4'],['A pup did tug the sock.','tug','t → u → g','🐕 〰️ 🧦','#dceff5'],['The sock fell in mud.','fell','f → e → ll','🧦 🟤','#fce1e6'],['Kiki got a big pot.','pot','p → o → t','👧 🪣','#fff4d6'],['Dip. Rub. The sock was red.','rub','r → u → b','🪣 🧦','#edf7f4'],['The pup got a mud sock.','sock','s → o → ck','🐕 🟤🧦','#dceff5']]},
{slug:'duck-muck',title:'The Duck in the Muck',job:'Teach',focus:'ck',cover:'🦆',pages:[['A duck sat in muck.','duck','d → u → ck','🦆 🟤','#edf7f4'],['The duck got stuck.','stuck','s → t → u → ck','🦆 🟤','#fff4d6'],['A hen did tug.','tug','t → u → g','🐔 〰️ 🦆','#dceff5'],['A pig did tug.','pig','p → i → g','🐷 〰️ 🦆','#fce1e6'],['The duck did sit.','duck','d → u → ck','🦆 🟤','#edf7f4'],['Then the duck did quack.','quack','qu → a → ck','🦆 〰️','#fff4d6'],['It was not stuck. It had a mud bed.','bed','b → e → d','🦆 🛏️','#dceff5']]},
{slug:'moth-bath',title:'The Moth and the Bath',job:'Teach',focus:'th',cover:'🦋',pages:[['A moth sat on the bath.','moth','m → o → th','🦋 🛁','#fff4d6'],['The bath got hot.','bath','b → a → th','🛁 ♨️','#fce1e6'],['The moth did hop.','moth','m → o → th','🦋 💨','#edf7f4'],['It hit the mat.','mat','m → a → t','🦋 ▰','#dceff5'],['The moth was not wet.','moth','m → o → th','🦋 ✨','#fff4d6'],['It had a nap on the mat.','nap','n → a → p','🦋 Zzz','#edf7f4'],['The bath had the moth mat.','bath','b → a → th','🛁 ▰ 🦋','#fce1e6']]},
{slug:'goat-boat',title:'The Goat on the Boat',job:'Stretch',focus:'oa',cover:'🐐',pages:[['A goat got on a boat.','goat','g → oa → t','🐐 ⛵','#dceff5'],['The goat had a red coat.','coat','c → oa → t','🐐 🧥','#fce1e6'],['A gust hit the boat.','boat','b → oa → t','💨 ⛵','#fff4d6'],['The coat fell in.','coat','c → oa → t','🧥 🌊','#edf7f4'],['The goat did not moan.','moan','m → oa → n','🐐 🤐','#dceff5'],['The goat got the coat.','coat','c → oa → t','🐐 🧥','#fce1e6'],['The goat sat on the coat. The boat did not tip.','goat','g → oa → t','🐐 🧥 ⛵','#fff4d6']]},
{slug:'rain-train',title:'Rain on the Train',job:'Stretch',focus:'ai',cover:'🚂',pages:[['Rain hit the train.','rain','r → ai → n','🌧️ 🚂','#dceff5'],['A snail got on the train.','snail','s → n → ai → l','🐌 🚂','#edf7f4'],['The train did go.','train','t → r → ai → n','🚂 💨','#fff4d6'],['The snail slid down.','snail','s → n → ai → l','🐌 ↘','#fce1e6'],['It hid in the mail.','mail','m → ai → l','🐌 ✉️','#dceff5'],['The rain did stop.','rain','r → ai → n','🌤️ 🚂','#edf7f4'],['The train had mail. The mail had a snail.','snail','s → n → ai → l','🚂 ✉️ 🐌','#fff4d6']]},
{slug:'red-kite',title:'Kaira and the Red Kite',job:'Stretch',focus:'i_e',cover:'🪁',pages:[['Kaira had a red kite.','kite','k → i_e → t','👧 🪁','#fce1e6'],['The kite did rise.','rise','r → i_e → s','🪁 ⬆️','#dceff5'],['A gust hit.','gust','g → u → s → t','💨 🪁','#fff4d6'],['The kite hid in a pine.','pine','p → i_e → n','🪁 🌲','#edf7f4'],['Dad got a big stick.','stick','s → t → i → ck','👨‍🦱 🪵','#fce1e6'],['Tap! The kite fell.','kite','k → i_e → t','🪵 🪁','#dceff5'],['Kaira got the kite. The pine got a red bit.','kite','k → i_e → t','👧 🪁 · 🌲 🎀','#fff4d6']]},
{slug:'moon-spoon',title:'The Spoon and the Moon',job:'Stretch',focus:'oo',cover:'🥄',pages:[['A spoon sat in a mug.','spoon','s → p → oo → n','🥄 ☕','#edf7f4'],['The mug got a bump.','bump','b → u → m → p','☕ 💥','#fff4d6'],['The spoon shot up.','spoon','s → p → oo → n','🥄 ⬆️','#dceff5'],['It hit the moon.','moon','m → oo → n','🥄 🌙','#fce1e6'],['A bat got the spoon.','spoon','s → p → oo → n','🦇 🥄','#edf7f4'],['The spoon sat in the mug.','spoon','s → p → oo → n','🥄 ☕','#fff4d6'],['The moon had a spoon dent.','moon','m → oo → n','🌙 🥄','#dceff5']]},
{slug:'shell-shop',title:'The Shell in the Shop',job:'Teach',focus:'sh',cover:'🐚',pages:[['A gull got a shell.','shell','sh → e → ll','🐦 🐚','#fff4d6'],['The gull hid it in a bag.','bag','b → a → g','🐦 🛍️','#edf7f4'],['The bag had a rip.','rip','r → i → p','🛍️ ⚡','#fce1e6'],['The shell fell in a shop.','shell','sh → e → ll','🐚 🏪','#dceff5'],['It hit the shop bell.','shop','sh → o → p','🐚 🔔','#fff4d6'],['Ding! The gull ran.','gull','g → u → ll','🔔 🐦💨','#edf7f4'],['The shell got a job in the shop.','shell','sh → e → ll','🐚 🏪','#fce1e6']]},
{slug:'king-ring',title:'The King and the Ring',job:'Teach',focus:'ng',cover:'💍',pages:[['A king had a ring.','ring','r → i → ng','🤴 💍','#dceff5'],['A pig sat with the king.','king','k → i → ng','🐷 🤴','#fce1e6'],['The ring fell in the pig pen.','ring','r → i → ng','💍 🐷','#fff4d6'],['The pig did dig.','pig','p → i → g','🐷 🟤','#edf7f4'],['The ring got mud.','ring','r → i → ng','💍 🟤','#dceff5'],['The king did grin.','king','k → i → ng','🤴 😁','#fce1e6'],['The king put the ring on the pig.','ring','r → i → ng','🐷 💍','#fff4d6']]}
];
